// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one


INSERT INTO groups (name)
VALUES ($1)
ON CONFLICT (name) 
DO UPDATE 
  SET name = EXCLUDED.name
RETURNING id
`

// groups.sql
func (q *Queries) CreateGroup(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createGroup, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
