version: '2'
plugins:
- name: golang
  wasm:
    url: https://downloads.sqlc.dev/plugin/sqlc-gen-go_1.3.0.wasm
    sha256: e8206081686f95b461daf91a307e108a761526c6768d6f3eca9781b0726b7ec8
sql:
- schema: ../migrations/*.up.sql
  queries: ../internal/infrastructure/repository/queries/*.sql
  engine: postgresql

  gen:
    go:
      package: "queries"
      out: "../internal/infrastructure/repository/queries"
      sql_package: "pgx/v5"
      emit_empty_slices: true
      emit_pointers_for_null_types: true
      overrides:
        - db_type: "uuid"
          go_type:
            import: "github.com/google/uuid"
            type: "UUID"

        - db_type: "uuid"
          nullable: true
          go_type:
            import: "github.com/google/uuid"
            type: "UUID"
            pointer: true

        - db_type: "date"
          go_type:
            import: "github.com/hardfinhq/go-date"
            package: "date"
            type: "Date"

        - db_type: "date"
          nullable: true
          go_type:
            import: "github.com/hardfinhq/go-date"
            package: "date"
            type: "Date"
            pointer: true

        - db_type: "pg_catalog.timestamp"
          nullable: true
          go_type:
            import: "time"
            type: "Time"
            pointer: true

        - db_type: "text"
          go_type:
            type: "string"