mode: release # debug, release

server:
  address: :8080

logging:
  level: info
  # path: 

tracing: # jaeger, stdout
  # output: jaeger 
  # name: song-service-tracer
  # endpoint: localhost:4318

  output: stdout 

music_service:
  address: http://host.docker.internal:9091
  timeout: 5s