#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT_PATH=$SCRIPT_DIR"/.."
ENV_FILE_PATH=$PROJECT_ROOT_PATH"/.env"

CONFIG_PATH=./config/test-config.yaml
POSTGRES_ADDRESS=localhost
POSTGRES_PORT=54321
POSTGRES_USER=test_user
POSTGRES_PASSWORD=test_password
POSTGRES_DB=test_db
POSTGRES_SSLMODE=disable

echo "CONFIG_PATH=$CONFIG_PATH" > $ENV_FILE_PATH
echo "POSTGRES_ADDRESS=$POSTGRES_ADDRESS" >> $ENV_FILE_PATH
echo "POSTGRES_PORT=$POSTGRES_PORT" >> $ENV_FILE_PATH
echo "POSTGRES_USER=$POSTGRES_USER" >> $ENV_FILE_PATH
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> $ENV_FILE_PATH
echo "POSTGRES_DB=$POSTGRES_DB" >> $ENV_FILE_PATH
echo "POSTGRES_SSLMODE=$POSTGRES_SSLMODE" >> $ENV_FILE_PATH
